[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mysqli']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'bash start.sh'
